### ISSUE TITLE
Shure QLXD TX OFF Status delay

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-shure-wireless#14]
Just noticed in the last few betas (not sure which...) that a significant delay has been introduced in the TX OFF feedback item.  It works but delays 5-7 seconds before responding.  This was not the case in the past.  I have played with the metering times and no change.  The Channel status feedback and others works as expected almost instantly.  Any ideas?  
Thanks

**Comment by krocheck** [comment]
Which version of Companion are you running?  Did this change after you switched to a newer version?  Which status/value exactly are you referring to?

QLX-D doesn't have an explicit TX on/off status, its simply implied when a number of status fields send the 'unknown' value.  Also, metering for the QLX-D only defines the timing for actively receiving the antenna, rf level, and audio level (since those change continuously).  All other status values are sent asynchronously from the unit (even with metering disabled) as the values change, so there's no control over how quickly the value you're referring to can be received ... it gets sent whenever it gets sent.

**Comment by obcocav** [comment]
@krocheck .  Ill try to dig through the older releases and find the change but right now on Beta 4127.  

I use the feedback Transmitter off to send a message to the speaker to turn mic on if they didn't.  Didnt realize it was interpreted but had been working much more realtime until recently.

Thanks for all your work!

**Comment by krocheck** [comment]
Ah.  I forgot that feedback.  Yeah, that feedback is processed by checking:

**Comment by krocheck** [comment]
I'm going to close this, as this is outside Companion's control for how quickly it gets data from the receiver.
